# fly.toml app configuration file generated for municipalidadhuanchaco on 2024-07-02T15:27:45-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'municipalidadhuanchaco'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 4200
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
