# fly.toml app configuration file generated for municipalidad-de-huanchaco on 2024-06-11T12:09:29-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'municipalidad-de-huanchaco'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 4200
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
